# Production Environment Overlay for Gateway

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: microservices

commonLabels:
  app: api-gateway
  environment: prod
  deployment-target: production

commonAnnotations:
  config.kubernetes.io/origin: "gateway-repository"
  environment: production
  gateway.config.kubernetes.io/source: "gateway-repository"

patches:
  - path: gateway-patch.yaml
  - path: httproute-patch.yaml

configMapGenerator:
  - name: gateway-config
    behavior: merge
    literals:
      - environment=prod
      - log_level=warn
      - rate_limit_requests=1000
      - rate_limit_interval=60
      - ssl_enabled=true
      - monitoring_enabled=true
      - gateway_domain=api.microservices.ecp-project-476405.com
      - backup_domain=microservices.ecp-project-476405.com

secretGenerator:
  - name: gateway-prod-secrets
    literals:
      - ssl_cert_name=microservices-ssl-cert
      - security_policy=api-gateway-security-policy
    type: Opaque