# Kustomization for Gateway API resources
# Centralized gateway configuration management

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- gateway.yaml
- httproute.yaml
- backend-config.yaml

labels:
- pairs:
    app: api-gateway
    component: gateway-api
    version: v1.0.0

commonAnnotations:
  deployment.kubernetes.io/revision: "1"

# Namespace for all gateway resources
namespace: microservices