# Kustomization for Gateway API resources
# Centralized gateway configuration management

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: gateway-api-base
  labels:
    app: api-gateway
    component: gateway-api
    managed-by: terraform
  annotations:
    config.kubernetes.io/origin: "gateway-repository"

resources:
- gateway.yaml
- httproute.yaml
- backend-config.yaml

commonLabels:
  app: api-gateway
  component: gateway-api
  version: v1.0.0
  managed-by: terraform

commonAnnotations:
  config.kubernetes.io/origin: "gateway-repository"
  deployment.kubernetes.io/revision: "1"

# Namespace for all gateway resources
namespace: microservices

# Configuration for gateway-specific settings
configMapGenerator:
- name: gateway-config
  literals:
  - gateway_version=v1.0.0
  - managed_by=terraform
  - repository=gateway-repo
  - last_updated=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Generate secrets for gateway operations
secretGenerator:
- name: gateway-secrets
  literals:
  - gateway_key=placeholder
  type: Opaque