
# Security policies for API Gateway
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-gateway-network-policy
  namespace: microservices
  labels:
    app: api-gateway
    component: security
    managed-by: terraform
spec:
  podSelector:
    matchLabels:
      app: api-gateway
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: microservices
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: microservices
    ports:
    - protocol: TCP
      port: 8081  # Customer service
    - protocol: TCP
      port: 8082  # Catalog service
    - protocol: TCP
      port: 8083  # Order service
  - to: []  # Allow DNS resolution
    ports:
    - protocol: UDP
      port: 53
---
# Pod Security Policy for API Gateway
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: api-gateway-psp
  labels:
    app: api-gateway
    component: security
    managed-by: terraform
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: true
  seccompProfile:
    type: RuntimeDefault