# # Base Kustomization for Gateway
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# metadata:
#   name: gateway-api-base
#   labels:
#     app: api-gateway
#     component: gateway-api
#     managed-by: terraform
#   annotations:
#     config.kubernetes.io/origin: "gateway-repository"

resources:
- gateway.yaml
- httproute.yaml
- backend-config.yaml

labels:
  app: api-gateway
  component: gateway-api
  version: v1.0.0

commonAnnotations:
  config.kubernetes.io/origin: "gateway-repository"
  deployment.kubernetes.io/revision: "1"

namespace: microservices

configMapGenerator:
- name: gateway-config
  literals:
  - gateway_version=v1.0.0
  - repository=gateway-repo

secretGenerator:
- name: gateway-secrets
  literals:
  - gateway_key=placeholder
  type: Opaque