# # Base Kustomization for Gateway

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: gateway-base
  labels:
    app: api-gateway
    managed-by: terraform

namespace: microservices

resources:
  - namespace.yaml
  - gateway-api/
  - routing/
  - security/

labels:
  - pairs:
      app: api-gateway
      version: v1.0.0
      managed-by: terraform

annotations:
  - pairs:
      config.kubernetes.io/origin: "gateway-repository"
      deployment.kubernetes.io/revision: "1"

configMapGenerator:
- name: gateway-base-config
  literals:
  - environment=base
  - gateway_version=v1.0.0
  - managed_by=terraform