# # Base Kustomization for Gateway
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- gateway-api/
- routing/
# - security/

labels:
- pairs:
    app: api-gateway
    component: gateway-api
    version: v1.0.0

commonAnnotations:
  deployment.kubernetes.io/revision: "1"

namespace: microservices

configMapGenerator:
- name: gateway-config
  literals:
  - gateway_version=v1.0.0
  - repository=gateway-repo

secretGenerator:
- name: gateway-secrets
  literals:
  - gateway_key=placeholder
  type: Opaque