# Development Environment Overlay for Gateway
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: microservices-dev

commonLabels:
  app: api-gateway
  environment: dev
  deployment-target: development

commonAnnotations:
  config.kubernetes.io/origin: "gateway-repository"
  environment: development
  gateway.config.kubernetes.io/source: "gateway-repository"

patches:
- path: gateway-patch.yaml
- path: httproute-patch.yaml

configMapGenerator:
- name: gateway-config
  behavior: merge
  literals:
  - environment=dev
  - log_level=debug
  - rate_limit_requests=100
  - rate_limit_interval=60
  - ssl_enabled=false
  - monitoring_enabled=true
  - gateway_domain=dev-api.microservices.ecp-project-476405.com
  - backup_domain=dev-microservices.ecp-project-476405.com

secretGenerator:
- name: gateway-dev-secrets
  literals:
  - ssl_cert_name=dev-microservices-ssl-cert
  - security_policy=dev-api-gateway-security-policy
  type: Opaque