# Order Management Service Routing Configuration
# Segregated routing rules for order-related endpoints

apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: order-service-routes
  namespace: microservices
  labels:
    app: api-gateway
    component: routing
    service: order-management
    managed-by: terraform
  annotations:
    config.kubernetes.io/origin: "gateway-repository"
    service.kubernetes.io/target: "order-management-service"
spec:
  parentRefs:
  - name: microservices-gateway
    namespace: microservices
  hostnames:
  - "api.microservices.ecp-project-476405.com"
  - "microservices.ecp-project-476405.com"
  rules:
  # Order REST API endpoints
  - matches:
    - path:
        type: PathPrefix
        value: /api/v1/orders
    - headers:
      - name: "Content-Type"
        value: "application/json"
    backendRefs:
    - name: order-management-service
      port: 8083
      weight: 100
    filters:
    - type: RequestHeaderModifier
      requestHeaderModifier:
        add:
        - name: "X-Service-Route"
          value: "order-service"
        - name: "X-Gateway-Timestamp"
          value: "#{timestamp}"
        - name: "X-Service-Version"
          value: "v1.0.0"
        - name: "X-Routing-Source"
          value: "gateway-repository"

  # Order GraphQL endpoint
  - matches:
    - path:
        type: PathPrefix
        value: /api/v1/orders/graphql
    - headers:
      - name: "Content-Type"
        value: "application/json"
    backendRefs:
    - name: order-management-service
      port: 8083
      weight: 100
    filters:
    - type: RequestHeaderModifier
      requestHeaderModifier:
        add:
        - name: "X-Service-Route"
          value: "order-graphql"
        - name: "X-Service-Version"
          value: "v1.0.0"
        - name: "X-Routing-Source"
          value: "gateway-repository"

  # Order health check endpoint
  - matches:
    - path:
        type: PathPrefix
        value: /api/v1/orders/health
    backendRefs:
    - name: order-management-service
      port: 8083
      weight: 100
    filters:
    - type: RequestHeaderModifier
      requestHeaderModifier:
        add:
        - name: "X-Health-Check"
          value: "order-service"
        - name: "X-Routing-Source"
          value: "gateway-repository"