# Staging Environment Overlay for Gateway
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: microservices-staging

labels:
- pairs:
    app: api-gateway
    environment: staging
    deployment-target: staging

commonAnnotations:
  config.kubernetes.io/origin: "gateway-repository"
  environment: staging
  gateway.config.kubernetes.io/source: "gateway-repository"

patches:
- path: gateway-patch.yaml
- path: httproute-patch.yaml

configMapGenerator:
- name: gateway-config
  behavior: merge
  literals:
  - environment=staging
  - log_level=info
  - rate_limit_requests=500
  - rate_limit_interval=60
  - ssl_enabled=true
  - monitoring_enabled=true
  - gateway_domain=staging-api.microservices.ecp-project-476405.com
  - backup_domain=staging-microservices.ecp-project-476405.com

secretGenerator:
- name: gateway-staging-secrets
  literals:
  - ssl_cert_name=staging-microservices-ssl-cert
  - security_policy=staging-api-gateway-security-policy
  type: Opaque