# Staging Environment Overlay for Gateway
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: gateway-staging
  labels:
    app: api-gateway
    environment: staging
    managed-by: terraform
  annotations:
    config.kubernetes.io/origin: "gateway-repository"
    segregated-from: "customer-management-service"

resources:
- ../../base

namespace: microservices-staging

labels:
  - pairs:
      environment: staging
      deployment-target: staging

annotations:
  - pairs:
      environment: staging
      gateway.config.kubernetes.io/segregated: "true"
      gateway.config.kubernetes.io/source: "gateway-repository"

patches:
- path: gateway-patch.yaml
- path: httproute-patch.yaml

configMapGenerator:
- name: gateway-config
  behavior: merge
  literals:
  - environment=staging
  - log_level=info
  - rate_limit_requests=500
  - rate_limit_interval=60
  - ssl_enabled=true
  - monitoring_enabled=true
  - gateway_domain=staging-api.microservices.ecp-project-476405.com
  - backup_domain=staging-microservices.ecp-project-476405.com

secretGenerator:
- name: gateway-staging-secrets
  literals:
  - ssl_cert_name=staging-microservices-ssl-cert
  - security_policy=staging-api-gateway-security-policy
  type: Opaque